replicaCount: 1

image:
  repository: ghcr.io/serignegueye45/serignembaye-gueye-gitops-app
  tag: "5f6d64bd8a9e98e2f475ec61e779318792e23758"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
